// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RaynMaker.Cube.Service")>]
[<assembly: AssemblyProductAttribute("RaynMaker.Cube")>]
[<assembly: AssemblyDescriptionAttribute("RaynMaker.Cube")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2018")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RaynMaker.Cube.Service"
    let [<Literal>] AssemblyProduct = "RaynMaker.Cube"
    let [<Literal>] AssemblyDescription = "RaynMaker.Cube"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2018"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
