// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RaynMaker.Cube")]
[assembly: AssemblyProductAttribute("RaynMaker.Cube")]
[assembly: AssemblyDescriptionAttribute("RaynMaker.Cube")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "RaynMaker.Cube";
        internal const System.String AssemblyProduct = "RaynMaker.Cube";
        internal const System.String AssemblyDescription = "RaynMaker.Cube";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
    }
}
